export const DEMOVEHICLES = [
  {
    id: "tesla_sport",
    name: "Tesla Sport",
    description: "Fast and agile",
    type: "bike",
    sub_type: "Sport",
    price_per_day: 84,
    price_per_hour: 10,
    currency: "USD",
    availability: "Unavailable",
    color: "Yellow",
  },
  {
    id: "toyota_speedboat",
    name: "Toyota Speedboat",
    description: "Luxurious and spacious",
    type: "boat",
    sub_type: "Speedboat",
    price_per_day: 57,
    price_per_hour: 23,
    currency: "USD",
    availability: "Unavailable",
    color: "Blue",
  },
  {
    id: "ford_touring",
    name: "Ford Touring",
    description: "Fast and agile",
    type: "bike",
    sub_type: "Touring",
    price_per_day: 119,
    price_per_hour: 26,
    currency: "USD",
    availability: "Available",
    color: "Purple",
  },
  {
    id: "bmw_sailboat",
    name: "BMW Sailboat",
    description: "Luxurious and spacious",
    type: "boat",
    sub_type: "Sailboat",
    price_per_day: 147,
    price_per_hour: 24,
    currency: "USD",
    availability: "Unavailable",
    color: "Red",
  },
  {
    id: "audi_speedboat",
    name: "Audi Speedboat",
    description: "Luxurious and spacious",
    type: "boat",
    sub_type: "Speedboat",
    price_per_day: 64,
    price_per_hour: 14,
    currency: "USD",
    availability: "Unavailable",
    color: "Yellow",
  },
  {
    id: "porsche_sedan",
    name: "Porsche Sedan",
    description: "Stylish and comfortable",
    type: "car",
    sub_type: "Sedan",
    price_per_day: 83,
    price_per_hour: 24,
    currency: "USD",
    availability: "Unavailable",
    color: "Red",
  },
  {
    id: "mercedes_convertible",
    name: "Mercedes Convertible",
    description: "Stylish and comfortable",
    type: "car",
    sub_type: "Convertible",
    price_per_day: 122,
    price_per_hour: 20,
    currency: "USD",
    availability: "Unavailable",
    color: "Orange",
  },
  {
    id: "audi_cabin_cruiser",
    name: "Audi Cabin Cruiser",
    description: "Luxurious and spacious",
    type: "boat",
    sub_type: "Cabin Cruiser",
    price_per_day: 60,
    price_per_hour: 13,
    currency: "USD",
    availability: "Available",
    color: "Silver",
  },
  {
    id: "lamborghini_hatchback",
    name: "Lamborghini Hatchback",
    description: "Stylish and comfortable",
    type: "car",
    sub_type: "Hatchback",
    price_per_day: 149,
    price_per_hour: 21,
    currency: "USD",
    availability: "Unavailable",
    color: "Green",
  },
  {
    id: "toyota_sport",
    name: "Toyota Sport",
    description: "Fast and agile",
    type: "bike",
    sub_type: "Sport",
    price_per_day: 131,
    price_per_hour: 16,
    currency: "USD",
    availability: "Unavailable",
    color: "Blue",
  },
  {
    id: "audi_fishing",
    name: "Audi Fishing",
    description: "Luxurious and spacious",
    type: "boat",
    sub_type: "Fishing",
    price_per_day: 149,
    price_per_hour: 18,
    currency: "USD",
    availability: "Unavailable",
    color: "Red",
  },
  {
    id: "porsche_standard",
    name: "Porsche Standard",
    description: "Fast and agile",
    type: "bike",
    sub_type: "Standard",
    price_per_day: 90,
    price_per_hour: 18,
    currency: "USD",
    availability: "Unavailable",
    color: "Blue",
  },
  {
    id: "lamborghini_cruiser",
    name: "Lamborghini Cruiser",
    description: "Fast and agile",
    type: "bike",
    sub_type: "Cruiser",
    price_per_day: 99,
    price_per_hour: 11,
    currency: "USD",
    availability: "Available",
    color: "Purple",
  },
  {
    id: "tesla_speedboat",
    name: "Tesla Speedboat",
    description: "Luxurious and spacious",
    type: "boat",
    sub_type: "Speedboat",
    price_per_day: 95,
    price_per_hour: 26,
    currency: "USD",
    availability: "Available",
    color: "Gray",
  },
  {
    id: "tesla_sailboat",
    name: "Tesla Sailboat",
    description: "Luxurious and spacious",
    type: "boat",
    sub_type: "Sailboat",
    price_per_day: 109,
    price_per_hour: 13,
    currency: "USD",
    availability: "Available",
    color: "Red",
  },
  {
    id: "chevrolet_standard",
    name: "Chevrolet Standard",
    description: "Fast and agile",
    type: "bike",
    sub_type: "Standard",
    price_per_day: 61,
    price_per_hour: 15,
    currency: "USD",
    availability: "Available",
    color: "Blue",
  },
  {
    id: "audi_sailboat",
    name: "Audi Sailboat",
    description: "Luxurious and spacious",
    type: "boat",
    sub_type: "Sailboat",
    price_per_day: 137,
    price_per_hour: 18,
    currency: "USD",
    availability: "Available",
    color: "White",
  },
  {
    id: "porsche_touring",
    name: "Porsche Touring",
    description: "Fast and agile",
    type: "bike",
    sub_type: "Touring",
    price_per_day: 54,
    price_per_hour: 29,
    currency: "USD",
    availability: "Unavailable",
    color: "Blue",
  },
  {
    id: "honda_cabin_cruiser",
    name: "Honda Cabin Cruiser",
    description: "Luxurious and spacious",
    type: "boat",
    sub_type: "Cabin Cruiser",
    price_per_day: 129,
    price_per_hour: 11,
    currency: "USD",
    availability: "Available",
    color: "Green",
  },
  {
    id: "tesla_sport2",
    name: "Tesla Sport",
    description: "Fast and agile",
    type: "bike",
    sub_type: "Sport",
    price_per_day: 108,
    price_per_hour: 13,
    currency: "USD",
    availability: "Available",
    color: "Black",
  },
];
